MODEL:
  TYPE: dct-vit
  NAME: dct_vit_win7_224
  DROP_PATH_RATE: 0.2
  DCT_VIT:
    DEPTHS: [1, 1, 3, 1]
    SP_WIN_SIZE: [7, 7, 7, 7]
    SP_NUM_HEADS: [3, 6, 12, 24]
    CH_WIN_SIZE: [[7, 14, 28, 56], [7, 14, 28], [7, 14], [7]]
   CH_NUM_HEADS: [4, 6, 8, 16]